//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage2._5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public int Id { get; set; }
        public string RegNr { get; set; }
        public int Brand { get; set; }
        public string Model { get; set; }
        public int Wheel { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public System.DateTime CheckOutTime { get; set; }
        public bool Status { get; set; }
        public Nullable<int> VehicleType_Id { get; set; }
        public Nullable<int> Member_Id { get; set; }
    
        public virtual VehicleTypes VehicleTypes { get; set; }
        public virtual Members Members1 { get; set; }
    }
}
